spring:
  cloud:
    gateway:
      routes:
      - id : wallet-service
        uri: http://localhost:8088
        predicates :
          - path=/wallet/**
      - id : transaction-service
        uri: http://localhost:8090
        predicates:
          - path=/operation/**
  application:
    name: gateway-service
server:
  port: 8081